#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

# BACKUP THE APP MAIN DIR
ynh_backup "$install_dir"

# BACKUP THE DATA DIR
ynh_backup "$data_dir"

# BACKUP SYSTEM CONFIGURATION
ynh_backup "/etc/systemd/system/${app}-generate.service"
ynh_backup "/etc/systemd/system/${app}-generate.timer"

ynh_print_info "Backup script completed for $app."
