#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE NGINX FOR NEW URL
#=================================================

ynh_script_progression "Updating NGINX web server configuration..."
ynh_config_change_url_nginx

#=================================================
# DONE
#=================================================

ynh_script_progression "Change of URL completed for $app"
