#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND DISABLE SYSTEMD TIMER
#=================================================

ynh_script_progression "Stopping systemd timer..."

systemctl stop "${app}-generate.timer" 2>/dev/null || true
systemctl disable "${app}-generate.timer" 2>/dev/null || true

rm -f "/etc/systemd/system/${app}-generate.service"
rm -f "/etc/systemd/system/${app}-generate.timer"

systemctl daemon-reload 2>/dev/null || true

#=================================================
# REMOVE NGINX CONFIG
#=================================================

ynh_script_progression "Removing NGINX configuration..."

ynh_config_remove_nginx

#=================================================
# DONE
#=================================================

ynh_script_progression "Removal of $app completed"
