#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

# RESTORE THE APP MAIN DIR
ynh_script_progression "Restoring the app main directory..."
ynh_restore "$install_dir"
chown -R "$app:www-data" "$install_dir"

# RESTORE THE DATA DIRECTORY
ynh_script_progression "Restoring the data directory..."
ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

# RESTORE SYSTEM CONFIGURATION
ynh_script_progression "Restoring systemd timer..."
ynh_restore "/etc/systemd/system/${app}-generate.service"
ynh_restore "/etc/systemd/system/${app}-generate.timer"
chmod 644 "/etc/systemd/system/${app}-generate.service" "/etc/systemd/system/${app}-generate.timer"
systemctl daemon-reload
systemctl enable "${app}-generate.timer" --quiet
systemctl start "${app}-generate.timer"

# RELOAD NGINX
ynh_script_progression "Reloading NGINX web server..."
ynh_systemctl --service=nginx --action=reload

ynh_script_progression "Restoration completed for $app"
